### PR TITLE
Add deploy to render guide

### LINKED ISSUE #8: Create a self-hosting guide (similar to our existing Fly.io guide) for Render.com
/bounty $100

The fly.io guide links to our [fly.io](https://github.com/triggerdotdev/fly.io) repo, if it makes sense to also have a starting repo for Render.com, then part of this issue will be supplying that repo (you can push it to your account and then we can either fork it or you can transfer it over to us, if you don't want to keep it on your account).

### PR DESCRIPTION
**Pull request by Ashutosh-Bhadauriya**
Fixes #8 

/claim #8

Screenshot (62)

Screenshot (64)

### CODE REVIEW

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam FYI,  right now I'm redirecting the repo to one created in my profile, please fork the repo, I will update the link then or I can transfer the ownership. Thanks!

**Comment by ericallam** [comment]
This looks great! Yes please could you transfer ownership to the triggerdotdev organization? Once that's done we can merge and deploy this 👍

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam I can't create public repos to triggerdotdev. Is there any other way to do this?

Screenshot (67)

**Comment by ericallam** [comment]
Hmm, I can't seem to find it in my account or an email from GitHub. Could you try transferring it again?

**Comment by Ashutosh-Bhadauriya** [comment]
Just did it again please check

Screenshot (68)

**Comment by ericallam** [comment]
Great, that worked! Can you update the link now to point to https://github.com/triggerdotdev/render.com and then we can merge this 👍

**Comment by Ashutosh-Bhadauriya** [comment]
Awesome. Just updated the link

**Pull request merged**
