### PR TITLE
Improve openai docs

### LINKED ISSUE #10: Improve the OpenAI documentation
Currently our OpenAI documentation is pretty bare-bones, it would be great to flesh it out a bit more and highlight the `background*` tasks that make it so long-running OpenAI completions are possible on serverless by offloading them to Trigger.dev. Can refer to https://github.com/triggerdotdev/examples/tree/main/openai for inspiration.

### PR DESCRIPTION
**Pull request by Ashutosh-Bhadauriya**
Fixes #10 
/claim #10

### CODE REVIEW

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam please let me know your thoughts. Thanks!

**Comment by ericallam** [comment]
This is a good start, but I was hoping for some more examples being added to the docs.

**Comment by Ashutosh-Bhadauriya** [comment]
Oh okay, adding image generation example will be good too, so we want only two examples right or more?

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam added some examples, please let me know. Thanks!

**Comment by ericallam** [comment]
We've moved the docs back into our monorepo and I've incorporated your changes in to the docs now. Going to close this PR instead of merging it in

/tip $50

**Pull request closed without merging**
